# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

piqp_setup_dense <- function(P, c, A, b, G, h, x_lb, x_ub, settings) {
    .Call(`_piqp_piqp_setup_dense`, P, c, A, b, G, h, x_lb, x_ub, settings)
}

piqp_setup_sparse <- function(P, c, A, b, G, h, x_lb, x_ub, settings) {
    .Call(`_piqp_piqp_setup_sparse`, P, c, A, b, G, h, x_lb, x_ub, settings)
}

piqp_solve_dense <- function(solver_p) {
    .Call(`_piqp_piqp_solve_dense`, solver_p)
}

piqp_solve_sparse <- function(solver_p) {
    .Call(`_piqp_piqp_solve_sparse`, solver_p)
}

piqp_get_dims_dense <- function(solver_p) {
    .Call(`_piqp_piqp_get_dims_dense`, solver_p)
}

piqp_get_dims_sparse <- function(solver_p) {
    .Call(`_piqp_piqp_get_dims_sparse`, solver_p)
}

piqp_update_dense <- function(solver_p, P, c, A, b, G, h, x_lb, x_ub) {
    invisible(.Call(`_piqp_piqp_update_dense`, solver_p, P, c, A, b, G, h, x_lb, x_ub))
}

piqp_update_sparse <- function(solver_p, P, c, A, b, G, h, x_lb, x_ub) {
    invisible(.Call(`_piqp_piqp_update_sparse`, solver_p, P, c, A, b, G, h, x_lb, x_ub))
}

piqp_get_settings_dense <- function(solver_p) {
    .Call(`_piqp_piqp_get_settings_dense`, solver_p)
}

piqp_get_settings_sparse <- function(solver_p) {
    .Call(`_piqp_piqp_get_settings_sparse`, solver_p)
}

piqp_update_settings_dense <- function(solver_p, settings) {
    invisible(.Call(`_piqp_piqp_update_settings_dense`, solver_p, settings))
}

piqp_update_settings_sparse <- function(solver_p, settings) {
    invisible(.Call(`_piqp_piqp_update_settings_sparse`, solver_p, settings))
}

